### ISSUE TITLE
Restart docker container on content change

### ISSUE THREAD

**Issue by ThomasVdBerge** [puppetlabs/puppetlabs-docker#435]
Hey Guys,

What is the correct way in this puppet module to restart the docker container when another resource changes?

For example:

 ```
 file { "test.txt":
    ...
  }

  docker::run { 'test':
   ...
  }
```

How can I make sure the docker container restarts when the content of the file test.txt changes?

**Comment by davejrt** [comment]
You can use a notify attribute with your docker::run as the value ie:

```
  file { '/tmp/file.yaml':
   ensure => present,
   content => template("module/file.yaml"),
   notify => Docker::Run['myconatiner'],
  }

 docker::run {'mycontainer':
    image => 'myimage:1.0',
  }

**Comment by kwek** [comment]
@davejrt : Are you sure this is the expected behavior? I am also trying to use notify to trigger a container restart but it seems to ignore it. I see it executes in `docker::run` in `manifests/run.pp`, line 427 where it does do the exec below. However, two things:

 1. The unless scripts exits with status 0 (because the container is already running), so the whole exec doesn't take place. 
 2. Even if the unless doesn't restrict, it uses a docker `start` command where it should be `restart`

```
        exec { "start ${title} with docker":
          command     => "${docker_command} start ${sanitised_title}",
          unless      => $container_running_check,
          environment => $exec_environment,
          path        => $exec_path,
          provider    => $exec_provider,
          timeout     => $exec_timeout,
        }
```

This is on Ubuntu 18.04.1 LTS, Docker version 18.06.1-ce, build e68fc7a. Maybe i'm looking in the wrong place, any help is appreciated.

**Comment by NotNorom** [comment]
In case anyone stumbling across this needs to notify a docker_compose resource instead: It's `Docker_compose['name']`.
