### ISSUE TITLE
$service_name not correctly setting sysconfig locations

### ISSUE THREAD

**Issue by RXM307** [puppetlabs/puppetlabs-docker#49]
Somewhat Related to Issue #43

If you use docker-latest package
ie.
```
class { 'docker':
    package_name			=> 'docker-latest',
    service_name			=> 'docker-latest',
}
```

This does not set $service_config correctly as this is hardcoded in params.pp depending on which distro your running
ie.
```
      $service_config = "/etc/sysconfig/docker"
      $storage_config = "/etc/sysconfig/docker-storage"
      $storage_setup_file = "/etc/sysconfig/docker-storage-setup"
```

Should this logic be moved from params.pp to service.pp and set as variables?
ie.
```
      $service_config = "/etc/sysconfig/${service_name}"
      $storage_config = "/etc/sysconfig/${service_name}-storage"
      $storage_setup_file = "/etc/sysconfig/${service_name}-storage-setup"
```

or is it acceptable that you need to declare this?
ie.
```
class { 'docker':
	use_upstream_package_source 	=> false,
	docker_command			=> 'docker-latest',
	package_name			=> 'docker-latest',
	service_name			=> 'docker-latest',
	service_config			=> '/etc/sysconfig/docker-latest',
	storage_config			=> '/etc/sysconfig/docker-latest-storage',
	storage_setup_file		=> '/etc/sysconfig/docker-latest-storage-setup',
}
```

**Comment by davejrt** [comment]
Hi

Based on what I can tell, you've got an internal repo in which you're hosting packages called docker-latest instead of docker-engine or docker-ce. 

We've had a discussion internally and at this stage don't think this is a pattern we want to support in the module. If this becomes a more common we request we may revise that decision but for now we think the best practise is to follow the package naming and versioning from upstream, and thus that's what we'll reflect in the module.

**Comment by RXM307** [comment]
@davejrt docker-latest are the name of the slightly newer versions of docker packages from the Redhat Extra repo

https://access.redhat.com/articles/2317361
