### ISSUE TITLE
docker::compose::proxy regex is too aggressive

### ISSUE THREAD

**Issue by MatthewSchlosserTR** [puppetlabs/puppetlabs-docker#570]
## Describe the Bug
docker::compose::proxy regex only permits a single DNS subdomain.

http://host.example.com:80 matches

http://host.subdomain.example.com:80 does not match

## Expected Behavior
A valid URL should match.

## Steps to Reproduce

```
class { 'docker':
	use_upstream_package_source => false,
	version => 'latest',
	repo_opt => '--enablerepo=rhel7-extras',
	extra_parameters => '--data-root=/data/docker',
	proxy => 'http://proxy.subdomain.example.com:80',
	no_proxy => '.internal.example.com',
	docker_users => ['someuser'],
}

class { 'docker::compose':
	ensure => present,
	version => '1.25.1',
	proxy => 'http://proxy.subdomain.example.com:80',
}

```

## Error

Error: Error while evaluating a Function Call, validate_re(): "http://proxy.subdomain.example.com:80" does not match "^((http[s]?)?:\\/\\/)?([^:^@]+:[^:^@]+@|)([\\da-z\\.-]+)\\.([\\da-z\\.]{2,6})(:[\\d])?([\\/\\w \\.-]*)*\\/?$" (file: /my/path/modules/docker/manifests/compose.pp, line: 51, column: 5) on node mynode.subdomain.example.com

## Environment
 - Version latest
 - Platform RedHat 7

**Comment by FOTempel** [comment]
It's also doesn't match an IP address, localhost, localhost.localdomain and a whole slew of other perfectly valid configurations. Just remove the whole thing. But given the age of this issue, I doubt it'll ever happen.

In case you're wondering why you would ever want to that....I need to run a CNTLM locally because my corporate proxy doesn't allow basic authentication or unauthenticated proxy access, but I can't configure the puppetlabs-docker module to use it because someone thought it was a brilliant idea to put this regex in.

**Comment by kenyon** [comment]
The problem is that there is no pull request to fix the issue. Someone just needs to create one, then I expect it would be fixed relatively quickly in a release of the module.
