### ISSUE TITLE
how to create daemon.json file?.

### ISSUE THREAD

**Issue by krishnaiah2021** [puppetlabs/puppetlabs-docker#593]
## Use Case
As per DISA STIG Report, we need to create daemon.json file and give permissions to root user only.

## Describe the Solution You Would Like
Have a toggle feature to create daemon file and update the permission as per user request

## Describe Alternatives You've Considered
Manually create that file and update the params manually

## Additional Context
We need to have this file as per Federal requirements.

**Comment by vegaaz** [comment]
@krishnaiah-kunta I temporarily solved this with a template. Depending on the number of values you need, it gets nasty very fast... Because you need to make sure you have the right syntax.

Here a snippet:
`  
  $set_insecure_registries = undef,
  $set_dns = undef,
  $set_data_root = undef
(...)
if $set_insecure_registries or $set_dns or $set_data_root {
    file { '/etc/docker/daemon.json':
      ensure  => file,
      owner   => 'root',
      group   => 'root',
      mode    => '0644',
      content => template("${module_name}/docker/etc/docker/daemon.json.erb"),
      notify  => Class['docker::service']
    }
  }`


Template:
`{
  <%- if @set_insecure_registries -%>
   "insecure-registries": <%= @set_insecure_registries %><%- if @set_dns or @set_data_root -%>,<%- end %>
  <%- end -%>
  <%- if @set_dns -%>
   "dns": <%= @set_dns %><%- if @set_data_root -%>,<%- end %>
  <%- end -%>
  <%- if @set_data_root -%>
   "data-root": <%= @set_data_root %>
  <%- end -%>
}`

Pretty nasty but you don't have to change the daemon.json by hand.
Example:
`  class { 'project::docker':
    set_insecure_registries => '["nexus.FQDN:8082"]'
  }`
