### ISSUE TITLE
Docker Containers with Multiple Networks Have Invalid Escaping

### ISSUE THREAD

**Issue by pronetsweb** [puppetlabs/puppetlabs-docker#679]
## Describe the Bug
The shell escaping applied at https://github.com/puppetlabs/puppetlabs-docker/blob/2f5689d77ed8dee20b05225485bd97b6270bf120/lib/puppet/parser/functions/docker_run_flags.rb#L28 is incorrect.

## Expected Behavior
Outputted script should be valid & functional. Currently script will fail with errors like: 
**Error response from daemon: network bridge --net rocketchat not found**

## Steps to Reproduce
1. Create a docker::run statement with multiple networks in array
2. Apply config

## Environment
 - Version 3.12.1
 - CentOS 7

## Additional Context
A small test case showing the incorrect escaping:

![image](https://user-images.githubusercontent.com/33426869/99803417-6b4e6f80-2b07-11eb-82ad-6a8e0ec6e478.png)

It seems the correct code would be something like:
    flags << "--net #{opts['net'].map{ |network| network.shellescape}.join(" --net ")}"

![image](https://user-images.githubusercontent.com/33426869/99805050-eb75d480-2b09-11eb-86f5-97f7dab5bd0f.png)

**Comment by duckpuppy** [comment]
I have a further problem with this: If I manually correct the start scripts and restart the systemd service related to any docker service with multiple networks, the service fails to start. The problem is that it creates both the `--net <network>` directives in `docker create` AND separate `docker network connect <network>` commands in the script. Removing the `--net` directives from the create command and leaving the connect commands allows services to start properly. The fix may be more to remove the `--net` directives from anything with multiple networks rather than fix escaping.

**Comment by shane-davidson** [comment]
Also running in to this issue.

Maybe removing net from the docker_run_flags completely and just use the network connect statements?

```
<% if @net.is_a? String%>
/usr/bin/<%= @docker_command %> network connect <%= @net %> <%= @sanitised_title %>
<% end %>
<% if @net.is_a? Array%>
  <% @net.each do |n| %>
/usr/bin/<%= @docker_command %> network connect <%= n %> <%= @sanitised_title %>
  <% end %>
<% end %>
````

**Comment by jjw24** [comment]
Also got this issue preventing us from deploying to prd.
